Repository davdelcar/decide-single-morancos01, pull requests merged in 2023-12, with the labels that each got.

#32 Revert "Creación de ventana de perfil de usuarios"
  decide/authentication/forms.py
  decide/authentication/templates/login.html
  decide/authentication/templates/profile.html
  decide/authentication/templates/welcome.html
  decide/authentication/tests.py
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/census/templates/census/census.html
  decide/census/templates/census/import.html
  decide/census/test_views.py
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/local_settings.example.py
  decide/visualizer/templates/visualizer/visualizer.html
  requirements.txt
Labels: bug

#42 Interfaz traducida al español #6
  decide/authentication/templates/login.html
  decide/base/admin.py
  decide/base/migrations/0004_alter_auth_options_alter_auth_me_alter_auth_name.py
  decide/base/models.py
  decide/census/admin.py
  decide/census/migrations/0002_alter_census_options_alter_census_voter_id_and_more.py
  decide/census/models.py
  decide/census/templates/census/census.html
  decide/locale/en/LC_MESSAGES/django.mo
  decide/locale/en/LC_MESSAGES/django.po
  decide/locale/es/LC_MESSAGES/django.mo
  decide/locale/es/LC_MESSAGES/django.po
  decide/locale/test.py
  decide/mixnet/admin.py
  decide/mixnet/migrations/0005_alter_mixnet_options_alter_mixnet_auth_position_and_more.py
  decide/mixnet/models.py
  decide/store/admin.py
  decide/store/migrations/0004_alter_vote_options_alter_vote_voter_id_and_more.py
  decide/store/models.py
  decide/voting/admin.py
  decide/voting/migrations/0006_alter_question_options_alter_questionoption_options_and_more.py
  decide/voting/models.py
Labels: traducciones

#85 Davdelcar
  decide/voting/tests.py
Labels: bug, votaciones, autenticación, tests

#97 Codacy Badge
  README.md
Labels: codacy
